# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build -v ./...

    - id: semver-tag
      uses: gandarez/semver-action@master
      with:
        branching_model: "trunk-based"
        main_branch_name: "main"
        patch_pattern: "^fix:.+"
        minor_pattern: "^feat:.+"
        major_pattern: "^major:.+"
        build_pattern: "^build:.+"
        exclude_pattern: "^ignore:.+"

    - name: "Created tag"
      run: echo "tag ${{ steps.semver-tag.outputs.semver_tag }}"

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.semver-tag.outputs.semver_tag }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
