# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build -v ./...

    - name: sember-tag
      uses: Magikon/github-tag-action@v5.0.0
      id: tag
   
    - name: "Created tag"
      run: echo "tag ${{ steps.semver-tag.outputs.tag }}"

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.semver-tag.outputs.tag }}
        tag_name: ${{ github.ref }}
