# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build -v ./...

    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: main

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        draft: false
        makeLatest: true
        name: ${{ steps.semver.outputs.next }}
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.semver.outputs.next }}
        artifacts: eml-extractor.exe
